<?php

return [
    'articles' => [
        [
            'slug' => 'menerjemahkan-data-lapangan-menjadi-keputusan-cepat',
            'title' => 'Menerjemahkan Data Lapangan Menjadi Keputusan Cepat',
            'category' => 'Operational Insight',
            'image' => 'images/artikel/artikel1.png',
            'excerpt' => 'Tim kami tidak hanya mendokumentasikan kegiatan, tetapi mengubah temuan harian menjadi rekomendasi teknis yang bisa langsung dieksekusi di gudang, pabrik, dan area distribusi.',
            'published_at' => '11 April 2026',
            'reading_time' => '5 menit baca',
            'content' => [
                'Setiap kunjungan lapangan di PT. Multidaya Anugrah Perkasa dimulai dari observasi proses kerja aktual, bukan asumsi umum. Tim memetakan pola pemakaian baterai, alur charging, serta kondisi area kerja untuk melihat titik paling kritis yang memengaruhi produktivitas.',
                'Dari temuan tersebut, kami menyusun rekomendasi praktis yang bisa dijalankan langsung oleh tim operasional pelanggan. Fokusnya adalah menurunkan downtime, menjaga kestabilan performa forklift, dan memastikan setiap unit tetap aman digunakan dalam ritme kerja harian.',
                'Pendekatan berbasis data ini membuat keputusan teknis lebih cepat, terukur, dan relevan dengan kebutuhan industri. Hasil akhirnya adalah operasional yang lebih konsisten serta biaya perawatan yang lebih terkendali dalam jangka panjang.',
            ],
        ],
        [
            'slug' => 'pendampingan-berkelanjutan-setelah-implementasi',
            'title' => 'Pendampingan Berkelanjutan Setelah Implementasi',
            'category' => 'After Sales Program',
            'image' => 'images/artikel/artikel2.png',
            'excerpt' => 'Setiap instalasi diikuti evaluasi performa berkala untuk memastikan baterai forklift tetap stabil, aman, dan ekonomis dalam jangka panjang.',
            'published_at' => '09 April 2026',
            'reading_time' => '4 menit baca',
            'content' => [
                'Implementasi produk hanyalah tahap awal. PT. Multidaya Anugrah Perkasa menjalankan program pendampingan purnajual untuk memastikan baterai forklift bekerja sesuai target operasional pelanggan dari waktu ke waktu.',
                'Evaluasi berkala dilakukan pada parameter penting seperti siklus pakai, pola pengisian, dan kondisi fisik unit. Dengan data ini, tim dapat memberikan arahan perawatan yang tepat serta langkah antisipasi sebelum gangguan terjadi.',
                'Model layanan berkelanjutan ini membantu pelanggan menjaga performa armada tetap stabil, sekaligus menekan risiko biaya tak terduga akibat kerusakan yang terlambat ditangani.',
            ],
        ],
        [
            'slug' => 'membangun-budaya-operasional-yang-lebih-aman',
            'title' => 'Membangun Budaya Operasional yang Lebih Aman',
            'category' => 'People & Safety',
            'image' => 'images/artikel/artikel3.png',
            'excerpt' => 'Program training kami menekankan keseimbangan antara produktivitas dan keselamatan sehingga tim operasional memiliki SOP yang lebih terstruktur.',
            'published_at' => '07 April 2026',
            'reading_time' => '5 menit baca',
            'content' => [
                'Keselamatan kerja menjadi bagian utama dalam setiap program pendampingan PT. Multidaya Anugrah Perkasa. Kami menilai bahwa produktivitas tinggi hanya dapat dicapai jika prosedur kerja aman dijalankan secara disiplin oleh seluruh tim operasional.',
                'Materi pelatihan difokuskan pada praktik harian: proses inspeksi awal, standar charging yang benar, hingga respon cepat saat ditemukan indikasi penurunan performa baterai forklift. Seluruh sesi dirancang kontekstual sesuai kondisi site pelanggan.',
                'Dengan SOP yang lebih jelas dan mudah diterapkan, risiko operasional dapat ditekan, kualitas kerja meningkat, dan keberlangsungan penggunaan unit menjadi lebih terjaga.',
            ],
        ],
        [
            'slug' => 'mendalami-kebutuhan-lapangan-secara-langsung',
            'title' => 'Mendalami Kebutuhan Lapangan Secara Langsung',
            'category' => 'Visit Customer',
            'image' => 'images/artikel/artikel1.png',
            'excerpt' => 'PT Multidaya Anugrah Perkasa melakukan kunjungan ke PT Megasurya untuk memetakan kebutuhan pelanggan, memperkuat komunikasi teknis, dan memastikan solusi baterai forklift yang diberikan benar-benar sesuai ritme operasional.',
            'published_at' => '04 April 2026',
            'reading_time' => '4 menit baca',
            'content' => [
                'Kunjungan customer visit ke PT Megasurya menjadi langkah penting untuk memahami kebutuhan operasional secara menyeluruh. Tim kami berdiskusi langsung dengan pengguna unit untuk mendapatkan gambaran nyata tantangan yang terjadi di lapangan.',
                'Komunikasi teknis difokuskan pada kecocokan spesifikasi baterai, pola penggunaan harian, dan kebutuhan perawatan agar performa unit tetap stabil pada jam kerja tinggi.',
                'Dari kunjungan ini, PT. Multidaya Anugrah Perkasa merumuskan rekomendasi yang lebih presisi sehingga solusi yang diberikan tidak hanya tepat secara teknis, tetapi juga efektif bagi ritme kerja pelanggan.',
            ],
        ],
        [
            'slug' => 'evaluasi-bersama-untuk-kualitas-layanan-berkelanjutan',
            'title' => 'Evaluasi Bersama untuk Kualitas Layanan Berkelanjutan',
            'category' => 'Visit Customer',
            'image' => 'images/artikel/artikel2.png',
            'excerpt' => 'Kunjungan ke PT Wings difokuskan pada evaluasi performa layanan, penyelarasan kebutuhan teknis forklift, dan pembentukan strategi pendampingan yang lebih responsif untuk mendukung stabilitas operasional harian.',
            'published_at' => '02 April 2026',
            'reading_time' => '4 menit baca',
            'content' => [
                'Dalam kunjungan ke PT Wings, evaluasi dilakukan secara kolaboratif antara tim teknis kami dan tim operasional pelanggan. Tujuannya adalah memastikan setiap layanan purnajual memberi dampak langsung terhadap kelancaran aktivitas harian.',
                'Poin evaluasi meliputi kecepatan respon, akurasi diagnosis, serta efektivitas rekomendasi perawatan baterai forklift yang telah dijalankan. Data lapangan menjadi dasar utama dalam menyusun perbaikan layanan berikutnya.',
                'Dengan pendekatan ini, strategi pendampingan menjadi lebih adaptif dan selaras dengan kebutuhan aktual pengguna, sehingga kualitas layanan dapat terus meningkat secara berkelanjutan.',
            ],
        ],
        [
            'slug' => 'kolaborasi-strategis-untuk-peningkatan-efisiensi',
            'title' => 'Kolaborasi Strategis untuk Peningkatan Efisiensi',
            'category' => 'Visit Customer',
            'image' => 'images/artikel/artikel3.png',
            'excerpt' => 'Bersama Wilmar Group, tim kami membahas peningkatan efisiensi pemakaian baterai, pendekatan maintenance berbasis data, serta rencana penguatan layanan purnajual agar performa unit tetap optimal dalam jangka panjang.',
            'published_at' => '30 Maret 2026',
            'reading_time' => '5 menit baca',
            'content' => [
                'Pertemuan bersama Wilmar Group berfokus pada penyelarasan target efisiensi energi dengan kebutuhan operasional yang dinamis. Tim kami meninjau penggunaan unit secara menyeluruh untuk menemukan ruang perbaikan yang berdampak nyata.',
                'Pendekatan maintenance berbasis data diterapkan agar keputusan servis tidak lagi bersifat reaktif. Monitoring performa baterai dilakukan lebih terstruktur sehingga tindakan teknis dapat dilakukan di waktu yang tepat.',
                'Kolaborasi ini memperkuat komitmen PT. Multidaya Anugrah Perkasa dalam menghadirkan solusi jangka panjang yang mengutamakan efisiensi, keandalan unit, dan kesinambungan operasional pelanggan.',
            ],
        ],
        [
            'slug' => 'principal-visit-untuk-peningkatan-standar-layanan',
            'title' => 'Principal Visit untuk Peningkatan Standar Layanan',
            'category' => 'Principal Visit',
            'image' => 'images/artikel/artikel1.png',
            'excerpt' => 'PT Multidaya Anugrah Perkasa bersama principal Hawker melakukan evaluasi lapangan, pembaruan insight teknologi, serta penyelarasan standar layanan agar performa baterai pelanggan tetap konsisten dan andal.',
            'published_at' => '27 Maret 2026',
            'reading_time' => '4 menit baca',
            'content' => [
                'Agenda principal visit bersama Hawker diarahkan untuk menyamakan standar layanan lapangan dengan perkembangan teknologi terbaru. Evaluasi dilakukan pada proses implementasi, perawatan, dan kualitas dukungan teknis di site pelanggan.',
                'Tim principal dan tim lokal bekerja bersama untuk menilai efektivitas praktik yang berjalan, termasuk kesesuaian prosedur terhadap kebutuhan operasional di Indonesia.',
                'Hasil dari principal visit ini menjadi landasan untuk meningkatkan konsistensi layanan PT. Multidaya Anugrah Perkasa agar pelanggan memperoleh performa baterai yang lebih andal dari waktu ke waktu.',
            ],
        ],
        [
            'slug' => 'penguatan-kolaborasi-teknis-bersama-principal',
            'title' => 'Penguatan Kolaborasi Teknis Bersama Principal',
            'category' => 'Principal Visit',
            'image' => 'images/artikel/artikel2.png',
            'excerpt' => 'Dalam agenda principal visit Microtex, tim kami mendalami pembaruan teknologi baterai forklift, memperkuat koordinasi teknis, dan merumuskan pendekatan implementasi yang lebih presisi sesuai kebutuhan pelanggan di lapangan.',
            'published_at' => '24 Maret 2026',
            'reading_time' => '5 menit baca',
            'content' => [
                'Kegiatan principal visit bersama Microtex difokuskan pada transfer insight teknologi terbaru agar implementasi di lapangan semakin tepat sasaran. Diskusi teknis mencakup performa produk, durabilitas, dan strategi perawatan yang direkomendasikan.',
                'Koordinasi lintas tim diperkuat untuk mempercepat alur penyelesaian kebutuhan pelanggan, mulai dari identifikasi masalah hingga tindakan teknis yang terukur.',
                'Melalui kolaborasi ini, PT. Multidaya Anugrah Perkasa memastikan setiap penerapan solusi baterai forklift memiliki standar kualitas yang selaras dengan principal sekaligus relevan dengan kondisi operasional lokal.',
            ],
        ],
        [
            'slug' => 'komitmen-menampilkan-solusi-industri-terkini',
            'title' => 'Komitmen Menampilkan Solusi Industri Terkini',
            'category' => 'Exhibition',
            'image' => 'images/artikel/artikel1.png',
            'excerpt' => 'Partisipasi pada Forklift Indonesia 2023 menjadi momentum PT Multidaya Anugrah Perkasa untuk memperkenalkan inovasi produk baterai forklift, memperluas jaringan bisnis, dan menghadirkan solusi energi industri yang relevan bagi kebutuhan pelanggan.',
            'published_at' => '20 Maret 2026',
            'reading_time' => '4 menit baca',
            'content' => [
                'Partisipasi pada Forklift Indonesia 2023 menjadi ruang strategis bagi PT. Multidaya Anugrah Perkasa untuk memperkenalkan teknologi baterai forklift yang dirancang bagi kebutuhan industri modern.',
                'Selain menghadirkan produk, tim kami juga melakukan diskusi langsung dengan pelaku industri untuk memahami tantangan aktual seputar efisiensi energi, keandalan unit, dan kebutuhan layanan purnajual.',
                'Momentum ini mempertegas posisi perusahaan sebagai mitra solusi energi industri yang adaptif, kolaboratif, dan fokus pada hasil operasional jangka panjang.',
            ],
        ],
        [
            'slug' => 'memperkenalkan-teknologi-baterai-untuk-efisiensi-produksi',
            'title' => 'Memperkenalkan Teknologi Baterai untuk Efisiensi Produksi',
            'category' => 'Exhibition',
            'image' => 'images/artikel/artikel2.png',
            'excerpt' => 'Dalam event Manufacturing Surabaya 2025, kami mempresentasikan solusi baterai forklift berperforma tinggi untuk menunjang kelancaran proses produksi, sekaligus membuka kolaborasi baru bersama pelaku manufaktur nasional.',
            'published_at' => '16 Maret 2026',
            'reading_time' => '4 menit baca',
            'content' => [
                'Dalam Manufacturing Surabaya 2025, PT. Multidaya Anugrah Perkasa menampilkan solusi baterai forklift yang menekankan performa stabil untuk mendukung ritme produksi yang tinggi.',
                'Materi presentasi difokuskan pada dampak langsung terhadap proses manufaktur: pengurangan downtime, kecepatan siklus kerja, dan efisiensi biaya operasional.',
                'Keikutsertaan ini juga membuka ruang kolaborasi baru dengan berbagai pelaku manufaktur yang membutuhkan dukungan energi industri yang andal serta layanan teknis berkelanjutan.',
            ],
        ],
        [
            'slug' => 'solusi-energi-andal-untuk-operasional-industri-berat',
            'title' => 'Solusi Energi Andal untuk Operasional Industri Berat',
            'category' => 'Exhibition',
            'image' => 'images/artikel/artikel3.png',
            'excerpt' => 'Melalui keikutsertaan di Oil and Gas Indonesia 2024, PT Multidaya Anugrah Perkasa menghadirkan teknologi baterai forklift yang tahan terhadap kebutuhan operasional sektor energi dengan tuntutan keamanan dan keandalan tinggi.',
            'published_at' => '12 Maret 2026',
            'reading_time' => '5 menit baca',
            'content' => [
                'Sektor energi memiliki tuntutan operasional yang ketat, terutama pada aspek keselamatan dan keandalan. Di Oil and Gas Indonesia 2024, PT. Multidaya Anugrah Perkasa menampilkan solusi baterai forklift yang dirancang untuk kebutuhan kerja berat.',
                'Pendekatan kami menitikberatkan pada konsistensi performa di lingkungan kerja dengan intensitas tinggi, sekaligus memastikan dukungan teknis tetap responsif saat dibutuhkan.',
                'Dengan pengalaman lapangan yang kuat, perusahaan terus mendorong implementasi solusi energi yang aman, efisien, dan mampu mendukung produktivitas sektor industri berat secara berkelanjutan.',
            ],
        ],
        [
            'slug' => 'mendorong-operasional-ramah-lingkungan-berbasis-teknologi',
            'title' => 'Mendorong Operasional Ramah Lingkungan Berbasis Teknologi',
            'category' => 'Exhibition',
            'image' => 'images/artikel/artikel1.png',
            'excerpt' => 'Pada Solartech Indonesia 2024, kami memperkenalkan solusi baterai forklift yang efisien, berorientasi pada keberlanjutan, dan mendukung transisi operasional industri menuju sistem energi yang lebih hijau.',
            'published_at' => '08 Maret 2026',
            'reading_time' => '4 menit baca',
            'content' => [
                'Solartech Indonesia 2024 menjadi platform penting bagi PT. Multidaya Anugrah Perkasa untuk menegaskan komitmen terhadap solusi energi industri yang lebih berkelanjutan.',
                'Kami memperkenalkan teknologi baterai forklift yang efisien dalam konsumsi energi dan tetap memenuhi kebutuhan performa operasional harian di sektor logistik serta manufaktur.',
                'Arah ini sejalan dengan kebutuhan pelanggan yang ingin meningkatkan produktivitas sekaligus bergerak menuju praktik operasional yang lebih ramah lingkungan.',
            ],
        ],
        [
            'slug' => 'training-operasional-untuk-tim-lapangan',
            'title' => 'Training Operasional untuk Tim Lapangan',
            'category' => 'Training',
            'image' => 'images/artikel/artikel1.png',
            'excerpt' => 'PT Multidaya Anugrah Perkasa menyelenggarakan training baterai forklift kepada tim Kiat P6 sebagai upaya meningkatkan pemahaman teknis, perawatan, serta penggunaan baterai secara optimal guna mendukung operasional yang lebih efisien dan aman.',
            'published_at' => '04 Maret 2026',
            'reading_time' => '5 menit baca',
            'content' => [
                'Program training bersama tim Kiat P6 disusun untuk memperkuat kemampuan teknis operator dalam penggunaan dan perawatan baterai forklift secara tepat.',
                'Sesi pelatihan mencakup praktik harian yang langsung relevan di lapangan, mulai dari inspeksi awal, prosedur charging, hingga identifikasi gejala penurunan performa unit.',
                'Dengan peningkatan kompetensi ini, operasional harian menjadi lebih aman, lebih efisien, dan risiko gangguan kerja dapat ditekan secara signifikan.',
            ],
        ],
        [
            'slug' => 'penguatan-kompetensi-untuk-performa-lapangan',
            'title' => 'Penguatan Kompetensi untuk Performa Lapangan',
            'category' => 'Training',
            'image' => 'images/artikel/artikel2.png',
            'excerpt' => 'Training baterai forklift kepada tim Kiat Tambak Sawah dan Krian difokuskan pada praktik penggunaan yang benar, keselamatan kerja, serta perawatan berkala demi menjaga kelancaran operasional di lapangan.',
            'published_at' => '01 Maret 2026',
            'reading_time' => '4 menit baca',
            'content' => [
                'Pelatihan untuk tim Kiat Tambak Sawah dan Krian menitikberatkan pada penguatan disiplin operasional serta penerapan prosedur kerja yang aman dan konsisten.',
                'Tim kami membimbing peserta dalam praktik penggunaan baterai forklift yang benar agar unit dapat beroperasi dengan performa optimal tanpa mengabaikan aspek keselamatan.',
                'Pendekatan ini membantu pelanggan membangun standar kerja yang lebih kuat, sehingga produktivitas lapangan meningkat dengan risiko operasional yang lebih terkendali.',
            ],
        ],
        [
            'slug' => 'pendampingan-teknis-berbasis-kebutuhan-operasional',
            'title' => 'Pendampingan Teknis Berbasis Kebutuhan Operasional',
            'category' => 'Training',
            'image' => 'images/artikel/artikel3.png',
            'excerpt' => 'Kegiatan training untuk SAT menitikberatkan pada peningkatan pemahaman teknis, langkah perawatan harian, serta proses penggunaan baterai forklift yang efisien agar performa operasional tetap stabil.',
            'published_at' => '27 Februari 2026',
            'reading_time' => '4 menit baca',
            'content' => [
                'Pada sesi training bersama SAT, PT. Multidaya Anugrah Perkasa menyesuaikan materi dengan kebutuhan operasional aktual agar hasil pelatihan langsung terasa di lapangan.',
                'Pembahasan utama mencakup langkah perawatan harian yang sederhana namun berdampak besar terhadap kestabilan performa baterai forklift dan umur pakai unit.',
                'Pendampingan teknis berbasis kebutuhan ini membantu tim pelanggan bekerja lebih efektif, cepat mengambil keputusan, dan menjaga kelancaran operasional.',
            ],
        ],
        [
            'slug' => 'program-training-untuk-keamanan-dan-efisiensi',
            'title' => 'Program Training untuk Keamanan dan Efisiensi',
            'category' => 'Training',
            'image' => 'images/artikel/artikel1.png',
            'excerpt' => 'Pada sesi bersama TFJ, tim kami membahas praktik terbaik penggunaan baterai forklift, prosedur pengecekan keamanan, dan strategi perawatan agar unit tetap andal serta mendukung produktivitas harian.',
            'published_at' => '22 Februari 2026',
            'reading_time' => '5 menit baca',
            'content' => [
                'Sesi training bersama TFJ dirancang untuk menyeimbangkan dua prioritas utama: keamanan kerja dan efisiensi operasional. Kedua aspek ini menjadi dasar untuk menjaga performa unit dalam jangka panjang.',
                'Tim kami memandu praktik pemeriksaan keamanan sebelum dan sesudah penggunaan unit, sekaligus membahas strategi perawatan yang mudah diterapkan oleh operator di lapangan.',
                'Dengan pola kerja yang lebih terstruktur, pelanggan dapat mempertahankan keandalan baterai forklift, menekan gangguan operasional, dan menjaga produktivitas harian tetap tinggi.',
            ],
        ],
    ],
];